### ISSUE TITLE
./entrypoint.sh: No such file or directory

### ISSUE THREAD

**Issue by ftnext** [ftnext/action-concatenate-files#2]
It may not be able to be run as actions of other repositories because of absence of `entrypoint.sh`.

```yaml
      - name: Prepare doctest target
        uses: ftnext/action-concatenate-files@v1.0.0
        with:
          sources: ${{ steps.awesome_id.outputs.files }}
          destination: source/sut.rst.txt
```
